# Generated by Django 3.1.1 on 2020-10-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact_info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='external_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
