# Generated by Django 3.1.1 on 2020-10-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
