# Generated by Django 3.1.1 on 2020-10-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0005_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='slug',
            new_name='url',
        ),
    ]
