# Generated by Django 3.1.1 on 2020-10-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0006_auto_20201018_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='slug',
            new_name='url',
        ),
    ]
