# Generated by Django 3.1.1 on 2020-10-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0007_auto_20201018_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='url',
            new_name='slug',
        ),
    ]
