# Generated by Django 3.1.1 on 2020-10-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
