# Generated by Django 3.1.1 on 2020-10-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0010_auto_20201029_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='pfp'),
        ),
    ]
