# Generated by Django 3.1.1 on 2020-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0011_auto_20201030_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pfp'),
        ),
    ]
