language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: mXOByYtCL8vH12vit35IMNhiFuZjeBJPuCGGUJcAyUi80pbQtmMCa0L5W2ru4cqYbqjVtas4M01axbDOcU89ZGkQCEtnhx0/9si3Ku4nlkmgPddQkISSSbHgokBAZ9M9tyrki8dTMDXRpG2hxjuTCYAEIjPwYBg/QyyC2pleFjHfSoAE/uMzs4nS6nfI1uYaaGI7eFnc9/zNpdHrPHWWvYJLY4Ta80FR0R3kt546WjLQEesHgOqT2nywz1YAr7SyuLmn3jYMA7GkJG/zRjlb2jgEbAGkjdXykOBnllGaQlNYmih7UOaqRdvOZDKh6Xj4RnhrG5RsrPA4tUtdJECqpUSDvNVC9V5q94ovrcDXRJSbiBo5yHQQDGFoP0dIHSv9adwtt+bVEBi5hxUd7dQRnLjjPdp64gIH1wTb+QtVWMYCbjX8oMsIQnlxiV82z3viU8Y1u7lbS6oykUn64pR5agJg4VJuV4y4/SHUMzV3dk/+JNXaVOa/pmHWGaCn6aWHXKa5pckKf+X+dlS3urWYnA+6UJLIaLU7gs6eVh1XCME+1BcbzIFngq2eWRE0U5DGa4EO8XB9XMkT1hwzpqEyKn7DauQS/P+ZOhxm5IQlCVVqZNFm7FBhi5cqlGUaKsh6j/RFQqpWfQQbRZl2ze7eVXnQirECuugwsKA4ZCkb41Y=
  app: micro-donations
  on:
    repo: uva-cs3240-f20/project-2-19
